### ISSUE TITLE
Organize source code into a package

### ISSUE THREAD

**Issue by danlangford** [cgregurich/BankingApplication#2]
In my experience the “default” package has actually caused me some headache. I would advise you to migrate your code into a package. maybe before you work on #1 

a common convention is to use a reverseable or url. Your package could be `io.github.cgregurich`

And then for each portion of that package (split on `.`) make a new folder inside the last and store your code in there. Each java source file will need the `package` statement at the top. Your ide will help you

**Comment by danlangford** [comment]
You know I failed to realize that your code is currently on a package `gregurichfinalproject` so you can just close this issue if you don’t want to make any changes

**Comment by cgregurich** [comment]
Organized code into packages: DataAccessObjects, Windows, and Controllers

**Comment by danlangford** [comment]
FWIW another time you may want to explore organizing your code into various smaller packages. I see you tried that for a commit and rolled back. There may have been problems with where your FXML files were or how they were referenced. If you want to revisit that another time I would love to assist
