### ISSUE TITLE
implement a .gitignore

### ISSUE THREAD

**Issue by danlangford** [cgregurich/BankingApplication#3]
its good coding practice to not commit resources that are generated. for example you dont need to commit jar files because they are either downloaded from a dependency management tool like maven or they are compiled by java. a .gitignore can help make sure you dont accidentally commit generated resources or resources that should be developer specific. 

the `.gitignore` files goes in the root of your project. i like the http://gitignore.io web service for quickly getting a gitignore together based on your tech

so for this project you might copy all of this http://gitignore.io/api/java,linux,macos,maven,windows,eclipse,intellij,netbeans to create your first `.gitignore`

**Comment by bootersket** [comment]
I actually had a .gitignore that was autogenerated when I cloned the repository on my computer, but in trying to do some stuff, I deleted everything that was written in it (if I recall, it just had dist and build in it). So I copied and pasted the link you suggested, but I'm not sure how to continue from there. I tried to add and commit the project but it tells me 

"Your branch is up to date with 'origin/master'.

Untracked files:
        .gitignore

nothing added to commit but untracked files present"

**Comment by danlangford** [comment]
so you need to "add" the new file to be tracked by git.

`> git add .gitignore`
`> git commit -m "added a gitignore"`
`> git push`

**Comment by danlangford** [comment]
it would also be good practice to remove files that are being tracked that would not have been tracked if the gitignore was in place earlier. here is a blog post that details the simple process http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

**Comment by bootersket** [comment]
I believe I fixed it, let me know if you agree

**Comment by danlangford** [comment]
The cursory glance at your last commit looks perfect!
